run_config:
  data_source: https://archive.ics.uci.edu/ml/machine-learning-databases/undocumented/taylor/cloud.data
  output_dir: runs/
  author: ayush agarwal
  project: cloud app

create_dataset:
  columns:
    [
      "visible_mean",
      "visible_max",
      "visible_min",
      "visible_mean_distribution",
      "visible_contrast",
      "visible_entropy",
      "visible_second_angular_momentum",
      "IR_mean",
      "IR_max",
      "IR_min",
    ]
  classes:
    [
      { "start": 53, "end": 1077, "label": 0 },
      { "start": 1082, "end": 2105, "label": 1 },
    ]
  file_name: clouds.csv

train_config:
  model_name:  RandomForestClassifier
  params:
    n_estimators: 100
    max_depth: 10
  test_size: 0.2
  random_state: 42
  train_features : ['log_entropy', 'IR_norm_range', 'entropy_x_contrast']

eval_config:
  scores: accuracy_score
    roc_auc_score
  metrics: confusion_matrix
    classification_report

generate_features:
  calculate_norm_range:
    IR_norm_range:
      min_col: IR_min
      max_col: IR_max
      mean_col: IR_mean
  log_transform:
    log_entropy: visible_entropy
  multiply:
    entropy_x_contrast:
      col_a: visible_contrast
      col_b: visible_entropy

score_config:
  features : ['log_entropy', 'IR_norm_range', 'entropy_x_contrast']
  prob : True 

evaluation_config:
  metrics:
    - accuracy_score 
    - f1_score 
    - precision_score 
    - recall_score 
    - auc_roc_score 
  reports:
    - classification_report
    - confusion_matrix

aws_config:
  upload: True
  bucket_name: cloud-hw2-ayush
  prefix: experiments



